### ISSUE TITLE
Markdown: soft line breaks not being rendered correctly

### ISSUE THREAD

**Issue by tuzz** [alphagov/govuk-developer-docs#587] opened 2017-11-22 11:03 UTC
http://spec.commonmark.org/0.27/#soft-line-breaks

I used `ExternalDoc.fetch` to embed some markdown from GitHub. This markdown contained newlines within paragraphs. These newlines were rendered as `<br>` tags. The spec says they should have been rendered as newlines in the HTML or space characters. This breaks formatting.

I don't know if this issue is specific to `ExternalDoc.fetch` or whether it's for markdown within this project, too.

**Comment by deanwilson** [comment] 2019-08-15 07:57
No one has commented on this issue for 2 years and the versions involved have changed since it was raised so I'm closing this ticket. Please feel free to reopen if the issue is still present. Or just to say "Hello"

**Closed by deanwilson** 2019-08-15 07:57 UTC
