### ISSUE TITLE
Re: 'Architecture overview of GOV.UK applications'

### ISSUE THREAD

**Issue by Hassan089** [alphagov/govuk-developer-docs#2351] opened 2020-02-26 13:28 UTC
Problem with 'Architecture overview of GOV.UK applications' not showing the architecture (https://docs.publishing.service.gov.uk/manual/architecture.html)

**Comment by issyl0** [comment] 2020-03-03 15:56
The architecture diagram is embedded on the page from https://draw.io. It might be worth checking if you've got any browser extensions that may block requests to https://draw.io. 

I can't reproduce the "not showing" bit myself (even in incognito mode or on a different laptop), so I'm going to close this.

**Closed by issyl0** 2020-03-03 15:56 UTC

**Comment by ChrisBAshton** [comment] 2020-03-03 16:10
I could reproduce it myself earlier today (9:29am) and when I saw this issue 6 days ago. But I can confirm it seems to be working now. I wonder what happened?
